### ISSUE TITLE
Issue with upgrading two pods at the same time

### ISSUE THREAD

**Issue by jbbriel** [kpolszewski/rancher-gitlab-deploy#1]
Good morning or good afternoon,
   Currently i am receiving an issue when attempting to upgrade two pods in my ci script. I am going to leave below the script with the error below.
     `deploy:container:development:
    stage: deploy
    image: kpolszewski/rancher2-gitlab-deploy
    environment: development
    only:
      - develop
    script:
      - upgrade --cluster example --environment example --stack example --service example --new-image ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID} --rancher-url ${RANCHER_DEV_URL} --rancher-key ${RANCHER_DEV_KEY} --rancher-secret ${RANCHER_DEV_SECRET}
      - upgrade --cluster case --environment example --stack example --service example --new-image ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID} --rancher-url ${RANCHER_DEV_URL} --rancher-key ${RANCHER_DEV_KEY} --rancher-secret ${RANCHER_DEV_SECRET}`

**Error Below**
 `Traceback (most recent call last):
  File "/usr/local/bin/upgrade", line 11, in <module>
    load_entry_point('rancher-gitlab-deploy==1.5', 'console_scripts', 'rancher-gitlab-deploy')()
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rancher_gitlab_deploy-1.5-py2.7.egg/rancher_gitlab_deploy/cli.py", line 156, in main
    upgrade['annotations']['gitlab.com/updateTime'] = datetime.datetime.today().strftime("%Y%m%d%H%M%S");
KeyError: 'annotations'
ERROR: Job failed: exit code 1`

If i were to use only one script the pipeline deploys with no errors but if i use 2 i receive the error as shown.

**Comment by jbbriel** [comment]
Is there a work around for this?

**Comment by jbbriel** [comment]
still waiting for any response

**Comment by jbbriel** [comment]
SO on a further note i found out that i cant add to lines under the script so i had to add another deploy stage which isnt correct because when using rancher cattle i was able to add multiple lines under the script section

**Comment by kpolszewski** [comment]
Sorry, as stated in readme, this version was ported for my personal use and may contain some/a lot of bugs.
"Feel free to use it, however this version is probably buggy(and these bugs may eat your dog) as it was intended to be used just with single specific, personal use-case."

In current state of Rancher I would recommend to use directly kubectl to manage your multi-container deployments.

Best regards!
